# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "vncnt-hugo"
license = "MIT"
licenselink = "https://github.com/gamingrobot/vncnt-hugo/blob/master/LICENSE"
description = "A simple theme for your personal landing page."
homepage = "https://github.com/gamingrobot/vncnt-hugo/"
tags = ["minimal", "landingpage", "responsive", "fontawesome", "personal", "dark mode"]
features = ["responsive", "dark mode", "lightweight"]
min_version = "0.60"

[author]
  name = "fncnt"
  homepage = "https://github.com/fncnt/"

[original]
  name = "fncnt"
  homepage = "https://github.com/fncnt/"
  repo = "https://github.com/fncnt/vncnt-hugo"
